### ISSUE TITLE
App uses screen scraping instead of Twitter API

### ISSUE THREAD

**Issue by systemsplanet-zz** [TolstoyDotCom/more-speech#1]
[SearchRunRepliesBuilder.java](https://github.com/TolstoyDotCom/more-speech/blob/master/src/main/java/com/tolstoy/censorship/twitter/checker/app/helpers/SearchRunRepliesBuilder.java)

While I appreciate what you are trying to
accomplish with this app, and you put a lot into this code, you can't draw solid conclusions from code that does screen-scraping of twitter html. 

You even pointed this out with your comment:
```
 This is complicated because of Twitter's conversations setup. Whether
 intentionally or not, some tweets in the timeline don't have the actual
 ID of the tweet that was replied to. Instead, they have a conversation
 ID that's could be the ID of the tweet that was replied to, or it could
 be the ID of the initial tweet in a series. If someone else replies to
 their own tweet and you reply to their reply, the HTML of your timeline
 will have the initial tweet's ID.
 
 What that means is that in some cases this class has to load an additional
 page to find the right tweet listing. First the individual tweet page
 with the reply is loaded to get the ID of the tweet that was replied to.
 Then the individual tweet page is loaded per usual to get the correct
 tweet listing. **There may be cases where even that doesn't work, or the
 logic used to select the actual replied-to tweet doesn't work.**
 ```
You might be able to come close with the Twitter API, however, my guess is it will take a subpoena to get access to twitters database to know the real answer.

**Comment by TolstoyDotCom** [comment]
The app has two modes: replies from a user and replies to a user. The only mode affected by the issue you raise is the replies from, i.e., checking if your replies are shadowbanned. And, the only part of that that's affected is finding the replies in the first place. After I find the replies, scraping is fine because it's exactly like if a real user visited each page.

I don't have a problem because I tweet using custom code that uses the API. If I want to reply I write the tweet in the ".@username: this is a reply" form and indicate to the API that it's a reply to a specific tweet. That then appears in my public timeline in a way that works with the app: it has "Replying to @username" above the tweet. That's a me-only solution.

I tried other ways to get a reply to appear in a public timeline using the Twitter web UI and it didn't work. I know I've seen others with "Replying to" in their public timelines so perhaps there's a Twitter client that works like my custom code does.

The alternative is to use an app that has access to the user's account. That means the user would need to set up an app (which now requires phone verification last I checked) or authorize an app I'd provide. Then I could get all their replies even if they don't appear in their public timeline. I might provide such an app at a future date.

**Comment by systemsplanet-zz** [comment]
How can you distinguish between these "missing" tweets 
- twitter has deleted
- user has deleted
- twitter is hiding because it wants to censor 
- app didn't look deep enough for the tweet
- twitter is temporarily not showing a tweet due to rate-limiting a user?
- twitter is temporarily not showing a tweet due to rate-limiting for a DDOS?

How can you distinguish between these "found" tweets 
- twitter is showing normally
- twitter is only showing because it knows your user id is not on their enemy list
- twitter is showing based on an algo that says, "show if the user is being crawled" (eg requests per second are faster than a real user)

**Comment by TolstoyDotCom** [comment]
1. Since I wrote this the focus shifted from it as a shadowban checker to it being used to expose how heavily Twitter censors all kinds of users (and thus how those who pretend otherwise are wrong). Specifically, that means getting someone with an audience to cover [these reports](https://github.com/TolstoyDotCom/more-speech). The ACLU won't respond. EFF said they won't help with this app because they didn't write it. Breitbart and others continue to mislead about what Twitter does because it would spoil their narrative. A BuzzFeed reporter sounded interested but I haven't heard back. Other reporters have replied and then clammed up. Changing that is my primary focus and should be the primary focus of anyone who wants to help use the app to fight against what Twitter actually does.

2. Nevertheless, the latest version uses the Twitter API via a page at my site to return a JSON file that can then be uploaded into the app via the "Check itinerary" button. That resolves your primary concern. The itinerary system isn't perfect, but it's close enough to give an accurate idea of whether you're shadowbanned or not (at least on reply pages).

3. The app only does what a human user would do, it just does it automatically. All of your questions can be answered by "what would I see if I did this myself?" The app logs in to Twitter and visits pages. If you set the screen position to 0,0 you can see that in action. The only way for Twitter to tell the difference between that and a human user are things like IP addresses, the browser User Agent, and the specific sequence of pages visited. Google, Facebook, and even Ticketmaster might be sophisticated enough to realize it's not a human visitor, but Twitter - a company that seems to shadowban people based on if they have a number in their handle, that has double-encoded output, that thinks "Shohei Ohtan" is an Estonian phrase and "Suburban Lawns - Janitor" is a Romanian phrase, that has shown logged-in-only info when logged out, etc. etc. probably isn't in their league.

In any case, thanks for your interest and please help find a reporter to cover the reports link above.
